subject_combinations_data = [
    {"code": "A00", "subjects": ["toan", "ly", "hoa"], "mainSubject": "toan"},
    {"code": "A01", "subjects": ["toan", "ly", "anh"], "mainSubject": "toan"},
    {"code": "K01_LY", "subjects": ["toan", "van", "ly"]},
    {"code": "K01_HOA", "subjects": ["toan", "van", "hoa"]},
    {"code": "K01_SINH", "subjects": ["toan", "van", "sinh"]},
    {"code": "K01_TIN", "subjects": ["toan", "van", "tin"]},
    {"code": "B00", "subjects": ["toan", "hoa", "sinh"], "mainSubject": "toan"},
    {"code": "D01", "subjects": ["toan", "van", "anh"], "mainSubject": "toan"},
    {"code": "D07", "subjects": ["toan", "hoa", "anh"], "mainSubject": "toan"},
    {"code": "D26", "subjects": ["toan", "ly", "duc"], "mainSubject": "toan"},
    {"code": "D28", "subjects": ["toan", "ly", "nhat"], "mainSubject": "toan"},
    {"code": "D29", "subjects": ["toan", "ly", "phap"], "mainSubject": "toan"},
    {"code": "A02", "subjects": ["toan", "ly", "sinh"], "mainSubject": "toan"},
    {"code": "D01_FL1,2,3", "subjects": ["toan", "van", "anh"], "mainSubject": "anh"},
    {"code": "D04_FL1,2,3", "subjects": ["toan", "van", "trung"], "mainSubject": "trung"},
    
    # Các tổ hợp KHÔNG có môn chính
    {"code": "A00_KHONG_CO_MON_CHINH", "subjects": ["toan", "ly", "hoa"]},
    {"code": "A01_KHONG_CO_MON_CHINH", "subjects": ["toan", "ly", "anh"]},
    {"code": "B00_KHONG_CO_MON_CHINH", "subjects": ["toan", "hoa", "sinh"]},
    {"code": "D01_KHONG_CO_MON_CHINH", "subjects": ["toan", "van", "anh"]},
    {"code": "D04_KHONG_CO_MON_CHINH", "subjects": ["toan", "van", "trung"]},
    {"code": "D07_KHONG_CO_MON_CHINH", "subjects": ["toan", "hoa", "anh"]},
    {"code": "D26_KHONG_CO_MON_CHINH", "subjects": ["toan", "ly", "duc"]},
    {"code": "D28_KHONG_CO_MON_CHINH", "subjects": ["toan", "ly", "nhat"]},
    {"code": "D29_KHONG_CO_MON_CHINH", "subjects": ["toan", "ly", "phap"]},
    {"code": "A02_KHONG_CO_MON_CHINH", "subjects": ["toan", "ly", "sinh"]},
]
